name: Go CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23 

      - name: Install dependencies for CLI
        run: |
          cd cli
          go mod tidy

      - name: Run tests for CLI
        run: |
          cd cli
          go test ./... -v

      - name: Install dependencies for Service
        run: |
          cd service
          go mod tidy

      - name: Run tests for Service
        run: |
          cd service
          go test ./... -v
